# Generated by Django 4.2.14 on 2024-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='login_sms_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(default='23ea734b', max_length=8),
        ),
    ]
