# Generated by Django 4.2.14 on 2024-08-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('danger', 'Error'), ('warning', 'Warning')], default='info', max_length=15),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(default='69a5946e', max_length=8),
        ),
    ]
