# Generated by Django 4.2.14 on 2024-08-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_message_type_alter_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(default='9ad14a2e', max_length=8),
        ),
    ]
